# Numpy exercises


#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [2]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [14]:
a = np.zeros((10), dtype = int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [15]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [21]:
x= np.zeros((10), dtype = int)
x[4] = 5
print(x)

[0 0 0 0 5 0 0 0 0 0]


#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [24]:
x = np.arange(10,50) 
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [27]:
x = np.arange(0,51)
print(x[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [28]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [48]:
array1 = np.array([1,2,0,0,4,0])
print(array1 [array1 >= 1])
np.nonzero(array1)

[1 2 4]


(array([0, 1, 4], dtype=int64),)

In [3]:
array1 = np.array([1,2,0,0,4,0])
x = np.where(array1>0)
x[0]

array([0, 1, 4], dtype=int64)

#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [38]:
a = np.random.rand(3,3,3)
print(a)

[[[0.04071624 0.69110771 0.61582827]
  [0.31912948 0.61299752 0.08840959]
  [0.9320993  0.18071824 0.58096404]]

 [[0.62528406 0.69531678 0.8732952 ]
  [0.15726227 0.1393249  0.66615661]
  [0.32708105 0.19009588 0.52663743]]

 [[0.89709856 0.53668198 0.67814829]
  [0.39012032 0.64073922 0.57873137]
  [0.53059718 0.12882441 0.6574943 ]]]


10. Create a 10x10 array with random values and find the minimum and maximum values 

Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [40]:
x = np.random.rand(10,10)
xmin =x.min()
xmax = x.max()
print('min:', xmin)
print('max:', xmax)

min: 0.02406968022920708
max: 0.9891667163418479


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [45]:
x = np.random.randint(100, size=30)
print('original array:', x)
x.mean()

original array: [62 41 71 35  5 58 28 94 76 15 69 84 25 97 10 31 64 74 76  0 86 94 32 70
 26 71 44 80 74 84]


55.86666666666667

#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [50]:
x = np.arange(0,11)
x [((3 <= x) & (x<= 8))]

array([3, 4, 5, 6, 7, 8])

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [5]:
x = np.random.randint(1, 10, 20)
print(x)
x [x < 5]*2

[1 8 5 7 4 9 3 7 5 5 8 8 5 4 7 5 9 5 4 6]


array([2, 8, 6, 8, 8])

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [67]:
x = np.array([1, 5, 6, 2, -2, 23, 45])
result = np.where(x%2 ==0)
result[0]

array([2, 3, 4], dtype=int64)

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [69]:
x = np.arange(1,21)
result = np.where(x % 3 ==0)
x[result]

array([ 3,  6,  9, 12, 15, 18])

#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [79]:
x = np.zeros((5,5), dtype =int)
x+=np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 17. Create a 3x5 numpy array filled with random numbers from 1 to 10.

#### 17. Ստեղծեք 1-ից 10 պատահական թվերով լցված (3, 5) չափերով numpy array։

In [81]:
x = np.random.randint(1,10, size =(3,5))
x

array([[1, 2, 7, 8, 6],
       [9, 7, 3, 9, 4],
       [6, 6, 8, 2, 8]])

#### 18. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

#### 18. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [85]:
x = np.zeros(10, dtype = int)
x[5] = 3
x

array([0, 0, 0, 0, 0, 3, 0, 0, 0, 0])

#### 19. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

#### 19. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [86]:
x = np.arange(3,15)
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 20. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array. 

#### 20. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [6]:
import numpy as np
def nump(x):
    while x.mean() > 5:
        x = x/2
    else:
        return x

In [11]:
x = np.array([20,30,2,8])
nump(x)

#### 21. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an input and returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

#### 21. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [20]:
import numpy as np
def ran(y):
    for i in range(4):
        print(y[...,i:i+1]) 

In [21]:
y = np.random.randint(1,11,(5,4))
ran(y)

[[ 9]
 [ 3]
 [ 8]
 [10]
 [ 6]]
[[ 1]
 [10]
 [ 3]
 [ 6]
 [ 1]]
[[ 5]
 [ 8]
 [ 8]
 [10]
 [ 6]]
[[9]
 [2]
 [5]
 [3]
 [6]]


In [22]:
import numpy as np
def ran(y):
    for i in range(5):
        print(y[i,...]) 

In [24]:
y = np.random.randint(1,11,(5,4))
ran(y)

[3 8 7 9]
[1 4 8 9]
[ 7  9  1 10]
[ 7  1 10  4]
[8 4 4 6]
