In [ ]:
#HW1 module1

In [4]:
#HW2
def div(x,y):
    assert ((x != 0) & (y!=0)),"Can’t divide."
    return x/y

In [5]:
div(10,0)

AssertionError: Can’t divide.

In [46]:
#HW3
def example_func(my_list: list):
    sum_of_pairs=[]
    try:
        for i in range(len(my_list)-1):
            sum_of_pairs.append(my_list[i]+my_list[i+1])
        print('SumOfPairs: ', sum_of_pairs)
    except TypeError:
        print('Type error')

In [47]:
x = [1,2, 'hi']
print(x)
example_func(x)

[1, 2, 'hi']
Type error


In [61]:
#HW4
def UpperContent(fileName):
    try:
        myfile = open('g.txt', 'r')
        for line in myfile:
            print(line.upper())
        myfile.close()
    except FileNotFoundError:
        print('olala')
UpperContent('t.txt')

olala


In [21]:
#numpy 5
import numpy as np
x = np.random.randint(1,11,(3,5))
x

array([[9, 1, 1, 5, 8],
       [8, 6, 7, 2, 8],
       [8, 7, 7, 5, 7]])

In [5]:
#numpy 6
z = np.zeros(10, dtype=int)
z[5]=3
z

array([0, 0, 0, 0, 0, 3, 0, 0, 0, 0])

In [7]:
#numpy 7
y = np.arange(3,15)
y

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
#numpy 8
g = np.array([1, 3, 5, 2, 4, 5])
g1 =g.reshape(3,2)
g2=g.reshape(2,3)
print('g is: ', g)
print('g1 is:', g1)
print('g2 is:', g2)

g is:  [1 3 5 2 4 5]
g1 is: [[1 3]
 [5 2]
 [4 5]]
g2 is: [[1 3 5]
 [2 4 5]]


In [13]:
#numpy 9
import numpy as np
def num(z):
    while np.mean(z) > 5:
        z = z/2
    else:
        print(z)

In [14]:
z = np.array([10,20,4,8])
num(z)

[2.5 5.  1.  2. ]


In [1]:
#numpy 10
import numpy as np
def rand(x):
    for i in range(4):
        print(x[:,i])

In [2]:
x = np.random.randint(1,11,(5,4))
rand(x)

[ 7  1  3  4 10]
[5 9 5 6 9]
[3 7 2 1 1]
[ 1  2 10 10  3]


In [3]:
#numpy 10.2
import numpy as np
def rand(x):
    for i in range(5):
        print(x[i, :])

In [4]:
x = np.random.randint(1,11,(5,4))
rand(x)

[8 4 8 5]
[3 3 2 6]
[1 7 8 7]
[3 5 2 1]
[7 9 4 3]
